cluster: # This section will set variables for slurm from those set for jobs in Snakemake
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --ntasks={threads}
    --mem={resources.mem}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
    --mail-type={resources.mail_type}
    --mail-user={resources.mail_user}
    # --nodelist="zenith" # If this is set things will run only on zenith
default-resources: # These are defaults, Snakemake will overide them, so they should be low
  - partition=wrighton-hi,wrighton-low # Default partition for your lab or debug for me
  - ntasks=1
  - node=1
  - mem=100
  - time="01:00:00"
  - time="01:00:00"
  - mail_user="<your email>@colostate.edu" # set your email
  - mail_type="begin,end,fail"
# Defaults for Snakemake, not Slurm
restart-times: 0 # number of times to restart failing jobs (default 0)
max-jobs-per-second: 5 # max_jobs_per_second
max-status-checks-per-second: 1 # How often the run is checked
local-cores: 1 #  the number of provided local cores if in cluster mode (ignored without cluster support) (default 1)
jobs: 1
latency-wait: 60
keep-going: False
rerun-incomplete: False
printshellcmds: True
scheduler: greedy
use-conda: True # Even if you don't use conda this must be set
conda-prefix: '~/snake_conda_env'
